### ISSUE TITLE
This project cannot run in my PC

### ISSUE THREAD

**Issue by gamemun01** [mk30715/KMUTNB-TA-REPO#1]
my Pc install 
php version 5.1.6
apache version 2.4
 why ?

**Comment by mk30715** [comment]
I'm not sure 
need more software information your PC.

**Comment by gamemun01** [comment]
OS: CentOS 7
Software List:
.
.
.
.
.
.
.
.
:1234:

**Comment by mk30715** [comment]
ok plz update your software env.
php version 7
apache version 5
